\i /docker-entrypoint-initdb.d/scripts/create_auto_submissions.sql
\i /docker-entrypoint-initdb.d/scripts/create_roles.sql
\i /docker-entrypoint-initdb.d/scripts/create_users.sql
\i /docker-entrypoint-initdb.d/scripts/create_dpms.sql
\i /docker-entrypoint-initdb.d/scripts/create_dpm_groups.sql
\i /docker-entrypoint-initdb.d/scripts/create_user_dpms.sql
\i /docker-entrypoint-initdb.d/scripts/create_user_roles.sql
\i /docker-entrypoint-initdb.d/scripts/create_dpm_groups.sql
\i /docker-entrypoint-initdb.d/scripts/create_w2w_colors.sql
\i /docker-entrypoint-initdb.d/scripts/insert_roles.sql
\i /docker-entrypoint-initdb.d/scripts/insert_users.sql
\i /docker-entrypoint-initdb.d/scripts/insert_dpm_groups.sql
\i /docker-entrypoint-initdb.d/scripts/insert_w2w_colors.sql
\i /docker-entrypoint-initdb.d/scripts/insert_dpms.sql
