version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: uts-dpm-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uts_dpm
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
